#!/usr/bin/env python3
"""Keep the typed Swift string keys in sync with the String Catalog.

Localizable.xcstrings is the single source of truth. It is editable in Xcode's
String Catalog editor. This script derives the typed `L10n` accessors from it
so a key can never drift from the catalog, and reports untranslated entries.

    scripts/l10n.py generate   # rewrite Strings+Generated.swift
    scripts/l10n.py check      # exit 1 on drift or missing translations
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CATALOG = os.path.join(ROOT, "Resources", "Localizations", "Localizable.xcstrings")
GENERATED = os.path.join(
    ROOT, "XiangqiMobile", "App", "Localization", "Strings+Generated.swift"
)
REQUIRED_LANGUAGES = ("en", "zh-Hans", "zh-Hant")

SWIFT_KEYWORDS = {
    "class", "default", "deinit", "enum", "extension", "func", "import", "in",
    "init", "internal", "let", "operator", "private", "protocol", "public",
    "repeat", "return", "self", "static", "struct", "subscript", "super",
    "switch", "var", "where", "while", "true", "false", "nil", "continue",
}

# Number of format placeholders, so call sites can be checked by the compiler.
PLACEHOLDER = re.compile(r"%(?:(\d+)\$)?[@a-zA-Z]|%lld")


def load_catalog():
    with open(CATALOG, encoding="utf-8") as handle:
        return json.load(handle)


def placeholder_count(value):
    """Highest positional index, or the count of sequential placeholders."""
    tokens = re.findall(r"%(?:(\d+)\$)?(?:lld|[@a-zA-Z])", value)
    if not tokens:
        return 0
    positional = [int(index) for index in tokens if index]
    return max(positional) if positional else len(tokens)


def identifier(segment):
    parts = re.split(r"[^0-9A-Za-z]+", segment)
    parts = [part for part in parts if part]
    if not parts:
        raise ValueError("empty key segment")
    head = parts[0]
    name = head[0].lower() + head[1:] + "".join(p[0].upper() + p[1:] for p in parts[1:])
    if name[0].isdigit():
        name = "_" + name
    return "`" + name + "`" if name in SWIFT_KEYWORDS else name


def type_name(segment):
    parts = [p for p in re.split(r"[^0-9A-Za-z]+", segment) if p]
    return "".join(p[0].upper() + p[1:] for p in parts)


def build_tree(strings):
    """Nest dotted keys, e.g. home.hero.title -> {home: {hero: {title: leaf}}}."""
    tree = {}
    for key in sorted(strings):
        node = tree
        segments = key.split(".")
        for segment in segments[:-1]:
            node = node.setdefault(segment, {})
            if not isinstance(node, dict):
                raise SystemExit(f"key '{key}' collides with a parent key")
        leaf = segments[-1]
        if leaf in node:
            raise SystemExit(f"key '{key}' collides with a nested namespace")
        english = (
            strings[key]
            .get("localizations", {})
            .get("en", {})
            .get("stringUnit", {})
            .get("value", "")
        )
        node[leaf] = (key, english, strings[key].get("comment"))
    return tree


def escape(value):
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def render(node, indent, lines):
    pad = "    " * indent
    for name in sorted(node):
        child = node[name]
        if isinstance(child, dict):
            lines.append(f"{pad}public enum {type_name(name)} {{")
            render(child, indent + 1, lines)
            lines.append(f"{pad}}}")
            lines.append("")
        else:
            key, english, comment = child
            count = placeholder_count(english)
            if comment:
                lines.append(f"{pad}/// {comment}")
            lines.append(f'{pad}/// English: "{escape(english)}"')
            lines.append(
                f'{pad}public static let {identifier(name)} = '
                f'LocalizedKey("{escape(key)}", en: "{escape(english)}"'
                + (f", arguments: {count}" if count else "")
                + ")"
            )
    while lines and lines[-1] == "":
        lines.pop()


def generate_source(catalog):
    lines = [
        "// Generated by scripts/l10n.py from Resources/Localizations/Localizable.xcstrings.",
        "// Do not edit by hand: edit the String Catalog and re-run `scripts/l10n.py generate`.",
        "",
        "// swiftlint:disable all",
        "",
        "public enum L10n {",
    ]
    body = []
    render(build_tree(catalog["strings"]), 1, body)
    lines.extend(body)
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def missing_translations(catalog):
    problems = []
    for key, entry in sorted(catalog["strings"].items()):
        localizations = entry.get("localizations", {})
        for language in REQUIRED_LANGUAGES:
            unit = localizations.get(language, {}).get("stringUnit", {})
            if not unit.get("value"):
                problems.append(f"{key}: missing {language}")
            elif unit.get("state") not in ("translated", None):
                problems.append(f"{key}: {language} is '{unit.get('state')}'")
    return problems


def unused_keys(catalog):
    """Keys the app never references, found by scanning for the generated path."""
    used = set()
    swift_root = os.path.join(ROOT, "XiangqiMobile")
    for directory, _, files in os.walk(swift_root):
        for name in files:
            if not name.endswith(".swift") or name == "Strings+Generated.swift":
                continue
            with open(os.path.join(directory, name), encoding="utf-8") as handle:
                text = handle.read()
            for match in re.finditer(r"L10n(?:\.[A-Za-z0-9_`]+)+", text):
                used.add(match.group(0))
    declared = {}
    for key in catalog["strings"]:
        segments = key.split(".")
        path = "L10n." + ".".join(
            type_name(s) for s in segments[:-1] + []
        )
        accessor = identifier(segments[-1]).strip("`")
        path = "L10n" + "".join("." + type_name(s) for s in segments[:-1]) + "." + accessor
        declared[key] = path
    return sorted(key for key, path in declared.items() if path not in used)


def main():
    command = sys.argv[1] if len(sys.argv) > 1 else "generate"
    catalog = load_catalog()
    source = generate_source(catalog)

    if command == "generate":
        os.makedirs(os.path.dirname(GENERATED), exist_ok=True)
        with open(GENERATED, "w", encoding="utf-8") as handle:
            handle.write(source)
        print(f"Generated {len(catalog['strings'])} keys -> {os.path.relpath(GENERATED, ROOT)}")
        problems = missing_translations(catalog)
        if problems:
            print(f"warning: {len(problems)} untranslated entries")
        return 0

    if command == "check":
        failures = []
        existing = ""
        if os.path.exists(GENERATED):
            with open(GENERATED, encoding="utf-8") as handle:
                existing = handle.read()
        if existing != source:
            failures.append(
                "Strings+Generated.swift is stale; run `scripts/l10n.py generate`"
            )
        failures.extend(missing_translations(catalog))
        for key in unused_keys(catalog):
            failures.append(f"{key}: not referenced by any view")
        if failures:
            for failure in failures:
                print(f"error: {failure}", file=sys.stderr)
            return 1
        print(f"{len(catalog['strings'])} keys: translated, referenced, and in sync.")
        return 0

    print(__doc__, file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main())
