// Generated by scripts/l10n.py from Resources/Localizations/Localizable.xcstrings.
// Do not edit by hand: edit the String Catalog and re-run `scripts/l10n.py generate`.

// swiftlint:disable all

public enum L10n {
    public enum App {
        public enum Recovery {
            /// English: "The saved game could not be validated. Its file has been preserved."
            public static let message = LocalizedKey("app.recovery.message", en: "The saved game could not be validated. Its file has been preserved.")
            /// English: "Saved game"
            public static let title = LocalizedKey("app.recovery.title", en: "Saved game")
        }
    }

    public enum Board {
        /// English: "Xiangqi board"
        public static let label = LocalizedKey("board.label", en: "Xiangqi board")
        /// English: "Legal destination"
        public static let legalDestination = LocalizedKey("board.legalDestination", en: "Legal destination")
        /// English: "Practice board"
        public static let practice = LocalizedKey("board.practice", en: "Practice board")
        public enum River {
            /// River text, left half
            /// English: "楚 河"
            public static let left = LocalizedKey("board.river.left", en: "楚 河")
            /// River text, right half
            /// English: "漢 界"
            public static let right = LocalizedKey("board.river.right", en: "漢 界")
        }

        public enum Square {
            /// English: "Empty %@"
            public static let empty = LocalizedKey("board.square.empty", en: "Empty %@", arguments: 1)
            /// Side, piece, square, state
            /// English: "%1$@ %2$@, %3$@, %4$@"
            public static let occupied = LocalizedKey("board.square.occupied", en: "%1$@ %2$@, %3$@, %4$@", arguments: 4)
        }

        public enum State {
            /// English: "occupied"
            public static let occupied = LocalizedKey("board.state.occupied", en: "occupied")
            /// English: "selectable"
            public static let selectable = LocalizedKey("board.state.selectable", en: "selectable")
        }

        /// English: "Study board"
        public static let study = LocalizedKey("board.study", en: "Study board")
    }

    public enum Common {
        /// English: "Always"
        public static let always = LocalizedKey("common.always", en: "Always")
        /// English: "Cancel"
        public static let cancel = LocalizedKey("common.cancel", en: "Cancel")
        /// English: "Confirm"
        public static let confirm = LocalizedKey("common.confirm", en: "Confirm")
        /// English: "Done"
        public static let done = LocalizedKey("common.done", en: "Done")
        /// Placeholder for a missing value
        /// English: "—"
        public static let emptyValue = LocalizedKey("common.emptyValue", en: "—")
        /// English: "Hint"
        public static let hint = LocalizedKey("common.hint", en: "Hint")
        /// English: "Home"
        public static let home = LocalizedKey("common.home", en: "Home")
        /// English: "Moves"
        public static let moves = LocalizedKey("common.moves", en: "Moves")
        /// Separator between two player names
        /// English: "–"
        public static let nameSeparator = LocalizedKey("common.nameSeparator", en: "–")
        /// English: "Next"
        public static let next = LocalizedKey("common.next", en: "Next")
        /// English: "Off"
        public static let off = LocalizedKey("common.off", en: "Off")
        /// English: "OK"
        public static let ok = LocalizedKey("common.ok", en: "OK")
        /// English: "Previous"
        public static let previous = LocalizedKey("common.previous", en: "Previous")
        /// English: "Random"
        public static let random = LocalizedKey("common.random", en: "Random")
        /// English: "Restart"
        public static let restart = LocalizedKey("common.restart", en: "Restart")
        /// English: "Result"
        public static let result = LocalizedKey("common.result", en: "Result")
        /// English: "Resume"
        public static let resume = LocalizedKey("common.resume", en: "Resume")
        /// English: "Settings"
        public static let settings = LocalizedKey("common.settings", en: "Settings")
        /// English: "Source"
        public static let source = LocalizedKey("common.source", en: "Source")
    }

    public enum Game {
        /// English: "Confirm move"
        public static let confirmMove = LocalizedKey("game.confirmMove", en: "Confirm move")
        /// English: "Flip"
        public static let flip = LocalizedKey("game.flip", en: "Flip")
        public enum Hint {
            /// English: "Hint"
            public static let available = LocalizedKey("game.hint.available", en: "Hint")
            /// English: "Hint shown"
            public static let destination = LocalizedKey("game.hint.destination", en: "Hint shown")
            /// English: "Finding"
            public static let searching = LocalizedKey("game.hint.searching", en: "Finding")
            /// English: "Show square"
            public static let source = LocalizedKey("game.hint.source", en: "Show square")
        }

        /// English: "Leave game"
        public static let leave = LocalizedKey("game.leave", en: "Leave game")
        /// English: "Game menu"
        public static let menu = LocalizedKey("game.menu", en: "Game menu")
        public enum Message {
            /// English: "Pikafish returned a move that does not match the current game."
            public static let engineMismatch = LocalizedKey("game.message.engineMismatch", en: "Pikafish returned a move that does not match the current game.")
            /// English: "Game not saved"
            public static let notSaved = LocalizedKey("game.message.notSaved", en: "Game not saved")
        }

        /// English: "Moves"
        public static let movesAction = LocalizedKey("game.movesAction", en: "Moves")
        public enum Rail {
            /// English: "Pikafish · Level %lld"
            public static let engine = LocalizedKey("game.rail.engine", en: "Pikafish · Level %lld", arguments: 1)
            /// English: "OPPONENT"
            public static let opponent = LocalizedKey("game.rail.opponent", en: "OPPONENT")
            /// English: "PLAYER"
            public static let player = LocalizedKey("game.rail.player", en: "PLAYER")
            /// English: "TO MOVE"
            public static let toMove = LocalizedKey("game.rail.toMove", en: "TO MOVE")
            /// English: "You · %@"
            public static let you = LocalizedKey("game.rail.you", en: "You · %@", arguments: 1)
        }

        public enum Status {
            /// English: "Check · %@ to move"
            public static let check = LocalizedKey("game.status.check", en: "Check · %@ to move", arguments: 1)
            /// English: "Computer to move"
            public static let computerToMove = LocalizedKey("game.status.computerToMove", en: "Computer to move")
            /// English: "Draw · %@"
            public static let draw = LocalizedKey("game.status.draw", en: "Draw · %@", arguments: 1)
            /// English: "Reviewing move %1$lld of %2$lld"
            public static let reviewing = LocalizedKey("game.status.reviewing", en: "Reviewing move %1$lld of %2$lld", arguments: 2)
            /// English: "%@ to move"
            public static let sideToMove = LocalizedKey("game.status.sideToMove", en: "%@ to move", arguments: 1)
            /// English: "Pikafish is thinking…"
            public static let thinking = LocalizedKey("game.status.thinking", en: "Pikafish is thinking…")
            /// English: "%1$@ wins · %2$@"
            public static let wins = LocalizedKey("game.status.wins", en: "%1$@ wins · %2$@", arguments: 2)
            /// English: "Your move"
            public static let yourMove = LocalizedKey("game.status.yourMove", en: "Your move")
        }

        /// English: "Game unavailable"
        public static let unavailable = LocalizedKey("game.unavailable", en: "Game unavailable")
        /// English: "Undo"
        public static let undo = LocalizedKey("game.undo", en: "Undo")
    }

    public enum GameMenu {
        /// English: "The saved record uses the starting FEN and ordered UCI moves. Display notation is derived, so games can be replayed and exchanged without depending on the visual theme."
        public static let formatNote = LocalizedKey("gameMenu.formatNote", en: "The saved record uses the starting FEN and ordered UCI moves. Display notation is derived, so games can be replayed and exchanged without depending on the visual theme.")
        /// English: "UCI coordinates"
        public static let movesValue = LocalizedKey("gameMenu.movesValue", en: "UCI coordinates")
        /// English: "New game"
        public static let newGame = LocalizedKey("gameMenu.newGame", en: "New game")
        /// English: "Resign"
        public static let resign = LocalizedKey("gameMenu.resign", en: "Resign")
        /// English: "Resign this game?"
        public static let resignConfirm = LocalizedKey("gameMenu.resignConfirm", en: "Resign this game?")
        /// English: "Rules"
        public static let rules = LocalizedKey("gameMenu.rules", en: "Rules")
        /// English: "Save and leave"
        public static let saveAndLeave = LocalizedKey("gameMenu.saveAndLeave", en: "Save and leave")
        public enum Section {
            /// English: "Record format"
            public static let format = LocalizedKey("gameMenu.section.format", en: "Record format")
            /// English: "Game"
            public static let game = LocalizedKey("gameMenu.section.game", en: "Game")
        }

        /// English: "Share game record"
        public static let share = LocalizedKey("gameMenu.share", en: "Share game record")
    }

    public enum History {
        /// English: "Live position"
        public static let livePosition = LocalizedKey("history.livePosition", en: "Live position")
        /// Move pair number followed by a period
        /// English: "%lld."
        public static let moveNumber = LocalizedKey("history.moveNumber", en: "%lld.", arguments: 1)
        /// English: "Return to live"
        public static let returnToLive = LocalizedKey("history.returnToLive", en: "Return to live")
        /// English: "Moves · %lld"
        public static let title = LocalizedKey("history.title", en: "Moves · %lld", arguments: 1)
    }

    public enum Home {
        public enum Continue {
            /// English: "Returns to the saved position"
            public static let hint = LocalizedKey("home.continue.hint", en: "Returns to the saved position")
            /// English: "%1$@ · %2$lld moves"
            public static let subtitle = LocalizedKey("home.continue.subtitle", en: "%1$@ · %2$lld moves", arguments: 2)
            /// English: "Continue game"
            public static let title = LocalizedKey("home.continue.title", en: "Continue game")
        }

        public enum Hero {
            /// English: "Play, study, and sharpen your game—entirely offline."
            public static let subtitle = LocalizedKey("home.hero.subtitle", en: "Play, study, and sharpen your game—entirely offline.")
            /// English: "The board is ready."
            public static let title = LocalizedKey("home.hero.title", en: "The board is ready.")
        }

        public enum Mode {
            public enum Computer {
                /// English: "Challenge Pikafish offline"
                public static let subtitle = LocalizedKey("home.mode.computer.subtitle", en: "Challenge Pikafish offline")
            }

            public enum Learn {
                /// English: "Puzzles and master games"
                public static let subtitle = LocalizedKey("home.mode.learn.subtitle", en: "Puzzles and master games")
                /// English: "Learn and practice"
                public static let title = LocalizedKey("home.mode.learn.title", en: "Learn and practice")
            }

            public enum TwoPlayer {
                /// English: "Share this iPhone"
                public static let subtitle = LocalizedKey("home.mode.twoPlayer.subtitle", en: "Share this iPhone")
            }
        }

        public enum Section {
            /// English: "CHOOSE A MODE"
            public static let mode = LocalizedKey("home.section.mode", en: "CHOOSE A MODE")
            /// English: "BOARD THEME"
            public static let theme = LocalizedKey("home.section.theme", en: "BOARD THEME")
        }

        /// App wordmark, Chinese
        /// English: "象棋"
        public static let title = LocalizedKey("home.title", en: "象棋")
        /// App wordmark, Latin
        /// English: "XIANGQI"
        public static let wordmark = LocalizedKey("home.wordmark", en: "XIANGQI")
    }

    public enum Learn {
        public enum Category {
            /// English: "Endgames"
            public static let endgames = LocalizedKey("learn.category.endgames", en: "Endgames")
            /// English: "Full-game tactics"
            public static let fullGameTactics = LocalizedKey("learn.category.fullGameTactics", en: "Full-game tactics")
            /// English: "Games"
            public static let games = LocalizedKey("learn.category.games", en: "Games")
            /// English: "Mating practice"
            public static let matingPractice = LocalizedKey("learn.category.matingPractice", en: "Mating practice")
            /// English: "Middlegames"
            public static let middlegames = LocalizedKey("learn.category.middlegames", en: "Middlegames")
            /// English: "Openings"
            public static let openings = LocalizedKey("learn.category.openings", en: "Openings")
        }

        /// English: "Could not load records"
        public static let couldNotLoadRecords = LocalizedKey("learn.couldNotLoadRecords", en: "Could not load records")
        public enum Dataset {
            /// English: "Dataset by Yu-Han Tseng and Bo-Nian Chen. Source records are decoded, converted to UCI, and legality-validated; ambiguous or invalid records are excluded."
            public static let note = LocalizedKey("learn.dataset.note", en: "Dataset by Yu-Han Tseng and Bo-Nian Chen. Source records are decoded, converted to UCI, and legality-validated; ambiguous or invalid records are excluded.")
            /// English: "Study master games, openings, middlegames, endgames, and tactical positions entirely offline."
            public static let subtitle = LocalizedKey("learn.dataset.subtitle", en: "Study master games, openings, middlegames, endgames, and tactical positions entirely offline.")
            /// English: "Chinese Chess Practical Dataset"
            public static let title = LocalizedKey("learn.dataset.title", en: "Chinese Chess Practical Dataset")
        }

        /// English: "Dataset revision"
        public static let datasetRevision = LocalizedKey("learn.datasetRevision", en: "Dataset revision")
        /// English: "ECCO"
        public static let ecco = LocalizedKey("learn.ecco", en: "ECCO")
        /// English: "Learning library unavailable"
        public static let libraryUnavailable = LocalizedKey("learn.libraryUnavailable", en: "Learning library unavailable")
        /// English: "License"
        public static let license = LocalizedKey("learn.license", en: "License")
        /// English: "Loading library…"
        public static let loadingLibrary = LocalizedKey("learn.loadingLibrary", en: "Loading library…")
        /// English: "Loading records…"
        public static let loadingRecords = LocalizedKey("learn.loadingRecords", en: "Loading records…")
        /// English: "%lld plies"
        public static let plyCount = LocalizedKey("learn.plyCount", en: "%lld plies", arguments: 1)
        /// English: "%@ records"
        public static let recordCount = LocalizedKey("learn.recordCount", en: "%@ records", arguments: 1)
        /// English: "Player, event, or ECCO"
        public static let searchPrompt = LocalizedKey("learn.searchPrompt", en: "Player, event, or ECCO")
        public enum Section {
            /// English: "Browse"
            public static let browse = LocalizedKey("learn.section.browse", en: "Browse")
        }

        /// English: "Learn"
        public static let title = LocalizedKey("learn.title", en: "Learn")
        /// English: "Validated records"
        public static let validatedRecords = LocalizedKey("learn.validatedRecords", en: "Validated records")
    }

    public enum Licenses {
        /// English: "Bundled notice"
        public static let bundledNotice = LocalizedKey("licenses.bundledNotice", en: "Bundled notice")
        public enum Ccpd {
            /// English: "Yu-Han Tseng and Bo-Nian Chen (2026)"
            public static let authors = LocalizedKey("licenses.ccpd.authors", en: "Yu-Han Tseng and Bo-Nian Chen (2026)")
            /// English: "Creative Commons Attribution 4.0 International"
            public static let license = LocalizedKey("licenses.ccpd.license", en: "Creative Commons Attribution 4.0 International")
            /// English: "CC BY 4.0 license"
            public static let licenseLink = LocalizedKey("licenses.ccpd.licenseLink", en: "CC BY 4.0 license")
            /// English: "Chinese Chess Practical Dataset (CCPD)"
            public static let name = LocalizedKey("licenses.ccpd.name", en: "Chinese Chess Practical Dataset (CCPD)")
            /// English: "Xiangqi Mobile decodes the source text, converts Chinese notation to UCI, validates move legality, and indexes accepted records for offline study. Invalid or ambiguous records are excluded."
            public static let note = LocalizedKey("licenses.ccpd.note", en: "Xiangqi Mobile decodes the source text, converts Chinese notation to UCI, validates move legality, and indexes accepted records for offline study. Invalid or ambiguous records are excluded.")
            /// English: "Dataset source"
            public static let sourceLink = LocalizedKey("licenses.ccpd.sourceLink", en: "Dataset source")
        }

        public enum Engine {
            /// English: "Pikafish is distributed under GNU GPL version 3. The bundled notice and authors list are included with the application."
            public static let note = LocalizedKey("licenses.engine.note", en: "Pikafish is distributed under GNU GPL version 3. The bundled notice and authors list are included with the application.")
        }

        /// English: "GNU GPL v3"
        public static let gpl = LocalizedKey("licenses.gpl", en: "GNU GPL v3")
        public enum Section {
            /// English: "Computer engine"
            public static let engine = LocalizedKey("licenses.section.engine", en: "Computer engine")
            /// English: "Learning content"
            public static let learning = LocalizedKey("licenses.section.learning", en: "Learning content")
        }

        /// English: "Licenses"
        public static let title = LocalizedKey("licenses.title", en: "Licenses")
    }

    public enum Mode {
        /// English: "Play Computer"
        public static let computer = LocalizedKey("mode.computer", en: "Play Computer")
        /// English: "Two Players"
        public static let localTwoPlayer = LocalizedKey("mode.localTwoPlayer", en: "Two Players")
    }

    public enum NewGame {
        /// English: "Level"
        public static let level = LocalizedKey("newGame.level", en: "Level")
        public enum LevelDetail {
            /// English: "A quick Pikafish search for a more forgiving game."
            public static let _1 = LocalizedKey("newGame.levelDetail.1", en: "A quick Pikafish search for a more forgiving game.")
            /// English: "A responsive Pikafish opponent with credible tactics."
            public static let _2 = LocalizedKey("newGame.levelDetail.2", en: "A responsive Pikafish opponent with credible tactics.")
            /// English: "Consistent play for regular club players."
            public static let _3 = LocalizedKey("newGame.levelDetail.3", en: "Consistent play for regular club players.")
            /// English: "A focused opponent that looks further ahead."
            public static let _4 = LocalizedKey("newGame.levelDetail.4", en: "A focused opponent that looks further ahead.")
            /// English: "The strongest built-in search setting."
            public static let _5 = LocalizedKey("newGame.levelDetail.5", en: "The strongest built-in search setting.")
        }

        public enum LevelName {
            /// English: "Beginner"
            public static let _1 = LocalizedKey("newGame.levelName.1", en: "Beginner")
            /// English: "Club learner"
            public static let _2 = LocalizedKey("newGame.levelName.2", en: "Club learner")
            /// English: "Club player"
            public static let _3 = LocalizedKey("newGame.levelName.3", en: "Club player")
            /// English: "Expert"
            public static let _4 = LocalizedKey("newGame.levelName.4", en: "Expert")
            /// English: "Master"
            public static let _5 = LocalizedKey("newGame.levelName.5", en: "Master")
        }

        /// English: "Mode"
        public static let mode = LocalizedKey("newGame.mode", en: "Mode")
        /// English: "Red moves first."
        public static let redMovesFirst = LocalizedKey("newGame.redMovesFirst", en: "Red moves first.")
        public enum Replace {
            /// English: "Replace and start"
            public static let confirm = LocalizedKey("newGame.replace.confirm", en: "Replace and start")
            /// English: "The current unfinished game will be replaced by this new game."
            public static let message = LocalizedKey("newGame.replace.message", en: "The current unfinished game will be replaced by this new game.")
            /// English: "Replace the saved game?"
            public static let title = LocalizedKey("newGame.replace.title", en: "Replace the saved game?")
        }

        public enum Section {
            /// English: "Your side"
            public static let side = LocalizedKey("newGame.section.side", en: "Your side")
            /// English: "Computer strength"
            public static let strength = LocalizedKey("newGame.section.strength", en: "Computer strength")
            /// English: "Theme"
            public static let theme = LocalizedKey("newGame.section.theme", en: "Theme")
            /// English: "Time"
            public static let time = LocalizedKey("newGame.section.time", en: "Time")
        }

        /// English: "Start game"
        public static let start = LocalizedKey("newGame.start", en: "Start game")
        /// English: "New game"
        public static let title = LocalizedKey("newGame.title", en: "New game")
    }

    public enum Piece {
        /// English: "Advisor"
        public static let advisor = LocalizedKey("piece.advisor", en: "Advisor")
        /// English: "Cannon"
        public static let cannon = LocalizedKey("piece.cannon", en: "Cannon")
        /// English: "Chariot"
        public static let chariot = LocalizedKey("piece.chariot", en: "Chariot")
        /// English: "Elephant"
        public static let elephant = LocalizedKey("piece.elephant", en: "Elephant")
        /// English: "General"
        public static let general = LocalizedKey("piece.general", en: "General")
        /// English: "Horse"
        public static let horse = LocalizedKey("piece.horse", en: "Horse")
        /// English: "Soldier"
        public static let soldier = LocalizedKey("piece.soldier", en: "Soldier")
    }

    public enum Practice {
        /// English: "Choose a destination."
        public static let chooseDestination = LocalizedKey("practice.chooseDestination", en: "Choose a destination.")
        /// English: "Line complete. Well done."
        public static let completed = LocalizedKey("practice.completed", en: "Line complete. Well done.")
        /// English: "Correct. The recorded reply has been played."
        public static let correct = LocalizedKey("practice.correct", en: "Correct. The recorded reply has been played.")
        /// English: "Could not open practice"
        public static let couldNotOpen = LocalizedKey("practice.couldNotOpen", en: "Could not open practice")
        /// English: "Find the best move."
        public static let findBestMove = LocalizedKey("practice.findBestMove", en: "Find the best move.")
        /// English: "Hint: %@"
        public static let hintFormat = LocalizedKey("practice.hintFormat", en: "Hint: %@", arguments: 1)
        /// English: "Not the recorded move. Try again."
        public static let incorrect = LocalizedKey("practice.incorrect", en: "Not the recorded move. Try again.")
        /// English: "Mistakes: %lld"
        public static let mistakes = LocalizedKey("practice.mistakes", en: "Mistakes: %lld", arguments: 1)
        /// English: "Move %1$lld of %2$lld"
        public static let moveProgress = LocalizedKey("practice.moveProgress", en: "Move %1$lld of %2$lld", arguments: 2)
        /// English: "Opening practice…"
        public static let opening = LocalizedKey("practice.opening", en: "Opening practice…")
        /// English: "Study line"
        public static let studyLine = LocalizedKey("practice.studyLine", en: "Study line")
        /// English: "Practice"
        public static let title = LocalizedKey("practice.title", en: "Practice")
    }

    public enum Reason {
        /// English: "Checkmate"
        public static let checkmate = LocalizedKey("reason.checkmate", en: "Checkmate")
        /// English: "Repetition"
        public static let repetition = LocalizedKey("reason.repetition", en: "Repetition")
        /// English: "Resignation"
        public static let resignation = LocalizedKey("reason.resignation", en: "Resignation")
        /// English: "Stalemate"
        public static let stalemate = LocalizedKey("reason.stalemate", en: "Stalemate")
        /// English: "Time loss"
        public static let timeLoss = LocalizedKey("reason.timeLoss", en: "Time loss")
    }

    public enum Result {
        /// English: "Game complete"
        public static let complete = LocalizedKey("result.complete", en: "Game complete")
        /// English: "Draw"
        public static let draw = LocalizedKey("result.draw", en: "Draw")
        /// English: "Review moves"
        public static let review = LocalizedKey("result.review", en: "Review moves")
        public enum Summary {
            /// English: "Hints"
            public static let hints = LocalizedKey("result.summary.hints", en: "Hints")
            /// English: "Moves"
            public static let moves = LocalizedKey("result.summary.moves", en: "Moves")
            /// English: "Time"
            public static let time = LocalizedKey("result.summary.time", en: "Time")
        }

        /// English: "%@ wins"
        public static let wins = LocalizedKey("result.wins", en: "%@ wins", arguments: 1)
    }

    public enum Rules {
        /// English: "Moves one point diagonally inside the palace."
        public static let advisor = LocalizedKey("rules.advisor", en: "Moves one point diagonally inside the palace.")
        /// English: "Moves like a chariot, but captures by jumping exactly one intervening piece."
        public static let cannon = LocalizedKey("rules.cannon", en: "Moves like a chariot, but captures by jumping exactly one intervening piece.")
        /// English: "Moves any distance along a clear file or rank."
        public static let chariot = LocalizedKey("rules.chariot", en: "Moves any distance along a clear file or rank.")
        /// English: "Moves two points diagonally, cannot jump, and cannot cross the river."
        public static let elephant = LocalizedKey("rules.elephant", en: "Moves two points diagonally, cannot jump, and cannot cross the river.")
        /// English: "Moves one point orthogonally inside the palace. The generals may not face on an open file."
        public static let general = LocalizedKey("rules.general", en: "Moves one point orthogonally inside the palace. The generals may not face on an open file.")
        /// English: "Checkmate the opposing general. Red moves first. A side with no legal move loses."
        public static let goal = LocalizedKey("rules.goal", en: "Checkmate the opposing general. Red moves first. A side with no legal move loses.")
        /// English: "Moves one orthogonal step then one diagonal step; the first step cannot be blocked."
        public static let horse = LocalizedKey("rules.horse", en: "Moves one orthogonal step then one diagonal step; the first step cannot be blocked.")
        /// English: "Files are a–i and ranks are 0–9. A move such as b2e2 records its source and destination. The game stores the starting FEN plus this ordered move list for reliable replay and sharing."
        public static let notation = LocalizedKey("rules.notation", en: "Files are a–i and ranks are 0–9. A move such as b2e2 records its source and destination. The game stores the starting FEN plus this ordered move list for reliable replay and sharing.")
        public enum Section {
            /// English: "Goal"
            public static let goal = LocalizedKey("rules.section.goal", en: "Goal")
            /// English: "Notation"
            public static let notation = LocalizedKey("rules.section.notation", en: "Notation")
            /// English: "Pieces"
            public static let pieces = LocalizedKey("rules.section.pieces", en: "Pieces")
        }

        /// English: "Moves forward one point. After crossing the river it may also move sideways, never backward."
        public static let soldier = LocalizedKey("rules.soldier", en: "Moves forward one point. After crossing the river it may also move sideways, never backward.")
        /// English: "Rules"
        public static let title = LocalizedKey("rules.title", en: "Rules")
    }

    public enum Settings {
        /// English: "App language"
        public static let appLanguage = LocalizedKey("settings.appLanguage", en: "App language")
        /// English: "Computer"
        public static let computer = LocalizedKey("settings.computer", en: "Computer")
        /// English: "Confirm moves"
        public static let confirmMoves = LocalizedKey("settings.confirmMoves", en: "Confirm moves")
        /// English: "Coordinates"
        public static let coordinates = LocalizedKey("settings.coordinates", en: "Coordinates")
        public enum CoordinatesOption {
            /// English: "Red perspective"
            public static let redPerspective = LocalizedKey("settings.coordinatesOption.redPerspective", en: "Red perspective")
        }

        /// English: "Computer play uses the bundled Pikafish engine and NNUE network entirely on-device. No account or network access is required."
        public static let engineNote = LocalizedKey("settings.engineNote", en: "Computer play uses the bundled Pikafish engine and NNUE network entirely on-device. No account or network access is required.")
        /// English: "Haptics"
        public static let haptics = LocalizedKey("settings.haptics", en: "Haptics")
        /// English: "How to play"
        public static let howToPlay = LocalizedKey("settings.howToPlay", en: "How to play")
        public enum Language {
            /// English: "English"
            public static let english = LocalizedKey("settings.language.english", en: "English")
            /// English: "Simplified Chinese"
            public static let simplifiedChinese = LocalizedKey("settings.language.simplifiedChinese", en: "Simplified Chinese")
            /// English: "System Default"
            public static let system = LocalizedKey("settings.language.system", en: "System Default")
            /// English: "Traditional Chinese"
            public static let traditionalChinese = LocalizedKey("settings.language.traditionalChinese", en: "Traditional Chinese")
        }

        /// English: "Open-source and content licenses"
        public static let licenses = LocalizedKey("settings.licenses", en: "Open-source and content licenses")
        /// English: "Move record"
        public static let moveRecord = LocalizedKey("settings.moveRecord", en: "Move record")
        /// English: "Piece labels"
        public static let pieceLabels = LocalizedKey("settings.pieceLabels", en: "Piece labels")
        public enum PieceLabelsOption {
            /// English: "Simplified Chinese"
            public static let simplified = LocalizedKey("settings.pieceLabelsOption.simplified", en: "Simplified Chinese")
            /// English: "Traditional Chinese"
            public static let traditional = LocalizedKey("settings.pieceLabelsOption.traditional", en: "Traditional Chinese")
        }

        /// English: "Rules policy"
        public static let rulesPolicy = LocalizedKey("settings.rulesPolicy", en: "Rules policy")
        public enum Section {
            /// English: "About"
            public static let about = LocalizedKey("settings.section.about", en: "About")
            /// English: "Appearance"
            public static let appearance = LocalizedKey("settings.section.appearance", en: "Appearance")
            /// English: "Interaction"
            public static let interaction = LocalizedKey("settings.section.interaction", en: "Interaction")
            /// English: "Language"
            public static let language = LocalizedKey("settings.section.language", en: "Language")
            /// English: "Rules and records"
            public static let rules = LocalizedKey("settings.section.rules", en: "Rules and records")
        }

        /// English: "Sound effects"
        public static let sounds = LocalizedKey("settings.sounds", en: "Sound effects")
        /// English: "Theme"
        public static let theme = LocalizedKey("settings.theme", en: "Theme")
        /// English: "Settings"
        public static let title = LocalizedKey("settings.title", en: "Settings")
        /// English: "Version"
        public static let version = LocalizedKey("settings.version", en: "Version")
    }

    public enum Side {
        /// English: "Black"
        public static let black = LocalizedKey("side.black", en: "Black")
        /// English: "Red"
        public static let red = LocalizedKey("side.red", en: "Red")
    }

    public enum Study {
        /// English: "CCPD · CC BY 4.0 · Modified by decoding, notation normalization, and legality validation."
        public static let attribution = LocalizedKey("study.attribution", en: "CCPD · CC BY 4.0 · Modified by decoding, notation normalization, and legality validation.")
        /// English: "Bookmark"
        public static let bookmark = LocalizedKey("study.bookmark", en: "Bookmark")
        /// English: "Could not open record"
        public static let couldNotOpen = LocalizedKey("study.couldNotOpen", en: "Could not open record")
        /// English: "%lld."
        public static let moveNumber = LocalizedKey("study.moveNumber", en: "%lld.", arguments: 1)
        /// English: "Opening record…"
        public static let opening = LocalizedKey("study.opening", en: "Opening record…")
        /// English: "%1$lld / %2$lld"
        public static let plyProgress = LocalizedKey("study.plyProgress", en: "%1$lld / %2$lld", arguments: 2)
        /// English: "Practice"
        public static let practice = LocalizedKey("study.practice", en: "Practice")
        /// English: "The record is not present in this library."
        public static let recordMissing = LocalizedKey("study.recordMissing", en: "The record is not present in this library.")
        /// English: "Remove bookmark"
        public static let removeBookmark = LocalizedKey("study.removeBookmark", en: "Remove bookmark")
        /// English: "Study"
        public static let title = LocalizedKey("study.title", en: "Study")
    }

    public enum Theme {
        /// Accessibility label for a theme swatch
        /// English: "%@ theme"
        public static let accessibilityLabel = LocalizedKey("theme.accessibilityLabel", en: "%@ theme", arguments: 1)
        /// English: "Calm"
        public static let calm = LocalizedKey("theme.calm", en: "Calm")
        /// English: "Classic"
        public static let classic = LocalizedKey("theme.classic", en: "Classic")
        /// English: "Tournament"
        public static let tournament = LocalizedKey("theme.tournament", en: "Tournament")
    }

    public enum TimeControl {
        /// English: "Casual"
        public static let casual = LocalizedKey("timeControl.casual", en: "Casual")
        /// English: "15 min"
        public static let fifteenMinutes = LocalizedKey("timeControl.fifteenMinutes", en: "15 min")
        /// English: "10 min"
        public static let tenMinutes = LocalizedKey("timeControl.tenMinutes", en: "10 min")
    }
}
